### ISSUE TITLE
bot offline

### ISSUE THREAD

**Issue by vildhjerte** [jimlind/filmlinkd#2]
bot offline since 01/01/2023

**Comment by captaindooley** [comment]
Just got a big review dump on one out of three servers I have this installed on. Nothing on the other two. It immediately went make to saying "the application did not respond" to any commands

**Comment by vildhjerte** [comment]
> Just got a big review dump on one out of three servers I have this installed on. Nothing on the other two. It immediately went back to saying "the application did not respond" to any commands

same thing happened to me, seems the bot was online for a few minutes and is now back offline.

**Comment by jimlind** [comment]
Please join the Filmlinkd Discord to discuss the status of the bot.
https://discord.gg/deZ7EUguge
