### ISSUE TITLE
Something going on with missed diary entries

### ISSUE THREAD

**Issue by jimlind** [jimlind/filmlinkd#3]
For the sake of experimentation found that this specific user https://letterboxd.com/_chlochette/rss/ ends up having a bunch of missing entries.

- Black Swarn
- Everything Everywhere at Once
- The Other Boylen Girl

All didn't get logged but appear in the RSS feed and on web diary page. When I attempted to get them to show up on the feed they didn't have any problems rendering so that doesn't appear to be the issue.

Logs appear as if the Scraper is working as expected. They don't have specific film data but the quantity and the timing look correct. There are no logs for failed attempts to write the diary entry.

This leads me to believe that message attempts are getting filtered out as if they are believed to be duplicate entries.

**Comment by jimlind** [comment]
The channels that _chlochette are followed in are
- 961103742395121734
- 812883182390607933
With the 812 channel being a thread I created.

The only logs from that user are successes. None of the normal failure avenues are getting logged.
There are several routes that do not get logged so likely the failures came from them.
The expectation was that those avenues are not interesting so I have no clue what the logs will look like when I start mucking them up.

**Comment by whatsie-doing** [comment]
Did you ever identify a root cause for this? I am seeing it as well. I stopped using Letterboxd for a year or more and recently started again. https://letterboxd.com/whatsie/rss/ shows the activity but neither of the two channels subscribed via /follow is getting the updates.

**Comment by jimlind** [comment]
@whatsie-doing Please join the Discord Server for support.
